#!/usr/bin/env python
# -*- coding: utf-8 -*-
#title           : THINCLIENT Menu
#Omschijving     : Geeft een simpel menu weer dat interactief is/shows a menu which is interactive
#Made by         : Patrick Pigmans
#Made at         : 2nd of August 2016
#python_version  : 2.7.12/3.5.2
#=======================================================================#

import Tkinter
from Tkinter import *
import subprocess
import os
from os import system as cmd

def test():
    os.system('sudo xterm -into %d -geometry 160x38+0-0 -e overscan &' % wid)

def sysinfo():
    os.system('xterm -into %d -geometry 160x38+0-0 -e systeminfo')

def ipconf():
    os.system('xterm -into %d -geometry 160x38+0-0 -e ipconfig &' % wid)

def grpmw():
    os.system('xterm -into %d -sb -e firefox http://myworkplace.21groep.nl' % wid)

def lout():
    os.system('xterm -into %d -sb -e pkill python' % wid)

def rboot():
    os.system('xterm -into %d -sb -e sudo reboot' % wid)

def pwoff():
    os.system('xterm -into %d -sb -e sudo poweroff' % wid)

WINDOW_SIZE = "1440x900"
top = Tkinter.Tk()
top.geometry(WINDOW_SIZE)

Button1  = Tkinter.Button(top, text ="Systeem informatie opvragen", command=sysinfo)
Button1.pack()

Button2  = Tkinter.Button(top, text ="IP adres achterhalen", command = ipconf)
Button2.pack()

Button3  = Tkinter.Button(top, text ="Zwarte balken weghalen", command = test)
Button3.pack()

Button4 = Tkinter.Button(top, text = "21 Groep Myworkplace", command = grpmw)
Button4.pack()

Button5  = Tkinter.Button(top, text ="Uitloggen", command = lout)
Button5.pack()

Button6  = Tkinter.Button(top, text ="Herstarten", command = rboot)
Button6.pack()

Button7 = Tkinter.Button(top, text = "Afsluiten", command = pwoff)
Button7.pack()



termf = Frame(top, height=1000, width=1000)

termf.pack(fill=BOTH, expand=YES)
wid = termf.winfo_id()


def send_entry_to_terminal(*args):
    """*args needed since callback may be called from no arg (button)
   or one arg (entry)
   """
    cmd("%s" % (BasicCovTests))

if __name__ == "__main__":
        top.title('KEUZE MENU')
        top.mainloop()

